=== Adrxking/Big-Data/BDA/UD 2/DTD/Ejercicios/Ej2/ejemplo2.dtd
<!ELEMENT Autor (Nombre, Indice)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Indice (Elemento*)>
<!ELEMENT Elemento (#PCDATA|Subelemento)*>
<!ELEMENT Subelemento (#PCDATA|Subsubelemento)*>
<!ELEMENT Subsubelemento (#PCDATA)>

=== Adrxking/Big-Data/BDA/UD 2/DTD/Ejercicios/Ej2/Ejemplo2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Importamos un DTD Externo -->
<!-- <!DOCTYPE Autor SYSTEM "ejemplo2.dtd"> -->
<!DOCTYPE Autor [
    <!ELEMENT Autor (Nombre, Indice)>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT Indice (Elemento*)>
    <!ELEMENT Elemento (#PCDATA|Subelemento)*>
    <!ELEMENT Subelemento (#PCDATA|Subsubelemento)*>
    <!ELEMENT Subsubelemento (#PCDATA)>
]>
<Autor>
   <Nombre> Pedro Salinas </Nombre>
   <Indice>
		<Elemento> Biografía
			<Subelemento> Primeros años </Subelemento>
			<Subelemento> Matrimonio y cátedra </Subelemento>
			<Subelemento> Santander </Subelemento>
			<Subelemento> Guerra civil y exilio </Subelemento>
		</Elemento>
		<Elemento> Poeta del 27
			<Subelemento> Etapas poéticas </Subelemento>
			<Subelemento> Poeta del amor </Subelemento>
		</Elemento>
		<Elemento> Prosista </Elemento>
		<Elemento> Dramaturgo </Elemento>
		<Elemento> Obra
			<Subelemento> Poesía
				<Subsubelemento> Presagio, Madrid, Índice, 1923 </Subsubelemento>
				<Subsubelemento> Seguro azar, Madrid, Revista de Occidente, 1929 </Subsubelemento>
				<Subsubelemento> Fábula y signo, Madrid, Plutarco, 1931 </Subsubelemento>
				<Subsubelemento> La voz a ti debida, Madrid, Signo, 1933 </Subsubelemento>
				<Subsubelemento> Razón de amor, Madrid, Ediciones del Árbol; Cruz y Raya, 1936guel N. Lira, 1938 </Subsubelemento>
				<Subsubelemento> Lost Angel and Other Poems, Baltimore, The Johns Hopkins Press, 1938 (antología bilingüe con poemas inéditos. Trad. de Eleanor L. Thurnbull). </Subsubelemento>
				<Subsubelemento> Poesía junta, Buenos Aires, Losada, 1942 </Subsubelemento>
				<Subsubelemento> El contemplado (Mar; poema), México, Nueva Floresta; Stylo, 1946 </Subsubelemento>
				<Subsubelemento> Todo más claro y otros poemas, Buenos Aires, Sudamericana, 1949 </Subsubelemento>
				<Subsubelemento> Poesías completas, Madrid, Aguilar, 1955 (incluye el libro inédito Confianza). </Subsubelemento>
				<Subsubelemento> Volverse y otros poemas, Milán, All'insegna del pesce d'oro, 1957 </Subsubelemento>
				<Subsubelemento> Poesía completas, Barcelona, Barral, 1971 </Subsubelemento>
			</Subelemento>
			<Subelemento> Teatro </Subelemento>
			<Subelemento> Traducciones </Subelemento>
			<Subelemento> Narrativa </Subelemento>
			<Subelemento> Ensayo </Subelemento>
			<Subelemento> Epistolario </Subelemento>
		</Elemento>
		<Elemento> Referencias </Elemento>
		<Elemento> Notas </Elemento>
		<Elemento> Bibliografía </Elemento>
   </Indice>
</Autor>
