<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Clasificacion [
    <!ELEMENT Clasificacion (Equipo+)>
    <!ELEMENT Equipo (#PCDATA)>

    <!ATTLIST Clasificacion Grupo CDATA #REQUIRED>
    <!ATTLIST Clasificacion Temporada CDATA #REQUIRED>
    <!ATTLIST Equipo PJ CDATA #REQUIRED>
    <!ATTLIST Equipo V CDATA #REQUIRED>
    <!ATTLIST Equipo E CDATA #REQUIRED>
    <!ATTLIST Equipo D CDATA #REQUIRED>
    <!ATTLIST Equipo GF CDATA #REQUIRED>
    <!ATTLIST Equipo GC CDATA #REQUIRED>
    <!ATTLIST Equipo DG CDATA #REQUIRED>
    <!ATTLIST Equipo Pts CDATA #REQUIRED>
]>

<Clasificacion
   Temporada="2019-2020"
   Grupo="A"
>
   <Equipo
      PJ="6"
      V="5"
      E="5"
      D="5"
      GF="17"
      GC="2"
      DG="15"
      Pts="16"
   > PSG
   </Equipo>
   <Equipo
      PJ="6"
      V="3"
      E="2"
      D="1"
      GF="14"
      GC="8"
      DG="6"
      Pts="11"
   > Real Madrid
   </Equipo>
   <Equipo
      PJ="6"
      V="0"
      E="3"
      D="3"
      GF="4"
      GC="12"
      DG="-8"
      Pts="3"
   > Club Brujas
   </Equipo>
   <Equipo
      PJ="6"
      V="0"
      E="2"
      D="4"
      GF="1"
      GC="14"
      DG="-13"
      Pts="2"
   > Galatasaray
   </Equipo>
</Clasificacion>
